// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/benchmark.dart';
import 'api/diagnostic_test.dart';
import 'api/focused_benchmark.dart';
import 'api/search_engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RegexBenchmarkerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SearchEnginePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RegexBenchmarker
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  RegexBenchmarker
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  Map<String, Map<String, bool>>
  dco_decode_Map_String_Map_String_bool_None_None(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  Map<String, int> dco_decode_Map_String_u_32_None(dynamic raw);

  @protected
  Map<String, BigInt> dco_decode_Map_String_u_64_None(dynamic raw);

  @protected
  Map<int, List<String>> dco_decode_Map_u_32_list_String_None(dynamic raw);

  @protected
  RegexBenchmarker
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    dynamic raw,
  );

  @protected
  SearchEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<SearchResult>>
  dco_decode_StreamSink_list_search_result_Sse(dynamic raw);

  @protected
  RustStreamSink<SearchStreamUpdate>
  dco_decode_StreamSink_search_stream_update_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BenchmarkResult dco_decode_benchmark_result(dynamic raw);

  @protected
  BenchmarkSuite dco_decode_benchmark_suite(dynamic raw);

  @protected
  BookCountResult dco_decode_book_count_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BenchmarkResult dco_decode_box_autoadd_benchmark_result(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  HighlightConfig dco_decode_box_autoadd_highlight_config(dynamic raw);

  @protected
  HighlightPattern dco_decode_box_autoadd_highlight_pattern(dynamic raw);

  @protected
  ResultGrouping dco_decode_box_autoadd_result_grouping(dynamic raw);

  @protected
  SearchResult dco_decode_box_autoadd_search_result(dynamic raw);

  @protected
  SemanticConfigInput dco_decode_box_autoadd_semantic_config_input(dynamic raw);

  @protected
  SemanticGroupingMode dco_decode_box_autoadd_semantic_grouping_mode(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WordMatchMode dco_decode_box_autoadd_word_match_mode(dynamic raw);

  @protected
  CountResult dco_decode_count_result(dynamic raw);

  @protected
  DocumentInput dco_decode_document_input(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FacetCount dco_decode_facet_count(dynamic raw);

  @protected
  FacetCountsResult dco_decode_facet_counts_result(dynamic raw);

  @protected
  HighlightConfig dco_decode_highlight_config(dynamic raw);

  @protected
  HighlightPattern dco_decode_highlight_pattern(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IndexCompatibility dco_decode_index_compatibility(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BenchmarkResult> dco_decode_list_benchmark_result(dynamic raw);

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<DocumentInput> dco_decode_list_document_input(dynamic raw);

  @protected
  List<FacetCount> dco_decode_list_facet_count(dynamic raw);

  @protected
  List<MergedSibling> dco_decode_list_merged_sibling(dynamic raw);

  @protected
  List<PdfIndexLine> dco_decode_list_pdf_index_line(dynamic raw);

  @protected
  List<PdfPageInput> dco_decode_list_pdf_page_input(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<(String, Map<String, bool>)>
  dco_decode_list_record_string_map_string_bool_none(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(String, int)> dco_decode_list_record_string_u_32(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  List<(int, List<String>)> dco_decode_list_record_u_32_list_string(
    dynamic raw,
  );

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<SemanticBookInput> dco_decode_list_semantic_book_input(dynamic raw);

  @protected
  List<SemanticBookLineInput> dco_decode_list_semantic_book_line_input(
    dynamic raw,
  );

  @protected
  List<SemanticSearchResult> dco_decode_list_semantic_search_result(
    dynamic raw,
  );

  @protected
  List<TestCase> dco_decode_list_test_case(dynamic raw);

  @protected
  MergedSibling dco_decode_merged_sibling(dynamic raw);

  @protected
  Map<String, int>? dco_decode_opt_Map_String_u_32_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BenchmarkResult? dco_decode_opt_box_autoadd_benchmark_result(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  HighlightConfig? dco_decode_opt_box_autoadd_highlight_config(dynamic raw);

  @protected
  HighlightPattern? dco_decode_opt_box_autoadd_highlight_pattern(dynamic raw);

  @protected
  ResultGrouping? dco_decode_opt_box_autoadd_result_grouping(dynamic raw);

  @protected
  SearchResult? dco_decode_opt_box_autoadd_search_result(dynamic raw);

  @protected
  SemanticGroupingMode? dco_decode_opt_box_autoadd_semantic_grouping_mode(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  WordMatchMode? dco_decode_opt_box_autoadd_word_match_mode(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PdfIndexLine dco_decode_pdf_index_line(dynamic raw);

  @protected
  PdfPageInput dco_decode_pdf_page_input(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  (String, Map<String, bool>) dco_decode_record_string_map_string_bool_none(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, int) dco_decode_record_string_u_32(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  (int, List<String>) dco_decode_record_u_32_list_string(dynamic raw);

  @protected
  ResultGrouping dco_decode_result_grouping(dynamic raw);

  @protected
  ResultsOrder dco_decode_results_order(dynamic raw);

  @protected
  SearchPageResult dco_decode_search_page_result(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  SearchScope dco_decode_search_scope(dynamic raw);

  @protected
  SearchStreamUpdate dco_decode_search_stream_update(dynamic raw);

  @protected
  SemanticBookInput dco_decode_semantic_book_input(dynamic raw);

  @protected
  SemanticBookLineInput dco_decode_semantic_book_line_input(dynamic raw);

  @protected
  SemanticConfigInput dco_decode_semantic_config_input(dynamic raw);

  @protected
  SemanticExecutedMode dco_decode_semantic_executed_mode(dynamic raw);

  @protected
  SemanticGroupingMode dco_decode_semantic_grouping_mode(dynamic raw);

  @protected
  SemanticIndexDiff dco_decode_semantic_index_diff(dynamic raw);

  @protected
  SemanticIndexingSummary dco_decode_semantic_indexing_summary(dynamic raw);

  @protected
  SemanticLexicalMode dco_decode_semantic_lexical_mode(dynamic raw);

  @protected
  SemanticRemoveResult dco_decode_semantic_remove_result(dynamic raw);

  @protected
  SemanticResetResult dco_decode_semantic_reset_result(dynamic raw);

  @protected
  SemanticResultSource dco_decode_semantic_result_source(dynamic raw);

  @protected
  SemanticRetrievalMode dco_decode_semantic_retrieval_mode(dynamic raw);

  @protected
  SemanticSearchResponse dco_decode_semantic_search_response(dynamic raw);

  @protected
  SemanticSearchResult dco_decode_semantic_search_result(dynamic raw);

  @protected
  SemanticStatus dco_decode_semantic_status(dynamic raw);

  @protected
  TestCase dco_decode_test_case(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WordMatchMode dco_decode_word_match_mode(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RegexBenchmarker
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  RegexBenchmarker
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, Map<String, bool>>
  sse_decode_Map_String_Map_String_bool_None_None(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, int> sse_decode_Map_String_u_32_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, BigInt> sse_decode_Map_String_u_64_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, List<String>> sse_decode_Map_u_32_list_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RegexBenchmarker
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    SseDeserializer deserializer,
  );

  @protected
  SearchEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<SearchResult>>
  sse_decode_StreamSink_list_search_result_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SearchStreamUpdate>
  sse_decode_StreamSink_search_stream_update_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BenchmarkResult sse_decode_benchmark_result(SseDeserializer deserializer);

  @protected
  BenchmarkSuite sse_decode_benchmark_suite(SseDeserializer deserializer);

  @protected
  BookCountResult sse_decode_book_count_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BenchmarkResult sse_decode_box_autoadd_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  HighlightConfig sse_decode_box_autoadd_highlight_config(
    SseDeserializer deserializer,
  );

  @protected
  HighlightPattern sse_decode_box_autoadd_highlight_pattern(
    SseDeserializer deserializer,
  );

  @protected
  ResultGrouping sse_decode_box_autoadd_result_grouping(
    SseDeserializer deserializer,
  );

  @protected
  SearchResult sse_decode_box_autoadd_search_result(
    SseDeserializer deserializer,
  );

  @protected
  SemanticConfigInput sse_decode_box_autoadd_semantic_config_input(
    SseDeserializer deserializer,
  );

  @protected
  SemanticGroupingMode sse_decode_box_autoadd_semantic_grouping_mode(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WordMatchMode sse_decode_box_autoadd_word_match_mode(
    SseDeserializer deserializer,
  );

  @protected
  CountResult sse_decode_count_result(SseDeserializer deserializer);

  @protected
  DocumentInput sse_decode_document_input(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FacetCount sse_decode_facet_count(SseDeserializer deserializer);

  @protected
  FacetCountsResult sse_decode_facet_counts_result(
    SseDeserializer deserializer,
  );

  @protected
  HighlightConfig sse_decode_highlight_config(SseDeserializer deserializer);

  @protected
  HighlightPattern sse_decode_highlight_pattern(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IndexCompatibility sse_decode_index_compatibility(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BenchmarkResult> sse_decode_list_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<DocumentInput> sse_decode_list_document_input(
    SseDeserializer deserializer,
  );

  @protected
  List<FacetCount> sse_decode_list_facet_count(SseDeserializer deserializer);

  @protected
  List<MergedSibling> sse_decode_list_merged_sibling(
    SseDeserializer deserializer,
  );

  @protected
  List<PdfIndexLine> sse_decode_list_pdf_index_line(
    SseDeserializer deserializer,
  );

  @protected
  List<PdfPageInput> sse_decode_list_pdf_page_input(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Map<String, bool>)>
  sse_decode_list_record_string_map_string_bool_none(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, int)> sse_decode_list_record_string_u_32(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(int, List<String>)> sse_decode_list_record_u_32_list_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<SemanticBookInput> sse_decode_list_semantic_book_input(
    SseDeserializer deserializer,
  );

  @protected
  List<SemanticBookLineInput> sse_decode_list_semantic_book_line_input(
    SseDeserializer deserializer,
  );

  @protected
  List<SemanticSearchResult> sse_decode_list_semantic_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<TestCase> sse_decode_list_test_case(SseDeserializer deserializer);

  @protected
  MergedSibling sse_decode_merged_sibling(SseDeserializer deserializer);

  @protected
  Map<String, int>? sse_decode_opt_Map_String_u_32_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BenchmarkResult? sse_decode_opt_box_autoadd_benchmark_result(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  HighlightConfig? sse_decode_opt_box_autoadd_highlight_config(
    SseDeserializer deserializer,
  );

  @protected
  HighlightPattern? sse_decode_opt_box_autoadd_highlight_pattern(
    SseDeserializer deserializer,
  );

  @protected
  ResultGrouping? sse_decode_opt_box_autoadd_result_grouping(
    SseDeserializer deserializer,
  );

  @protected
  SearchResult? sse_decode_opt_box_autoadd_search_result(
    SseDeserializer deserializer,
  );

  @protected
  SemanticGroupingMode? sse_decode_opt_box_autoadd_semantic_grouping_mode(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WordMatchMode? sse_decode_opt_box_autoadd_word_match_mode(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PdfIndexLine sse_decode_pdf_index_line(SseDeserializer deserializer);

  @protected
  PdfPageInput sse_decode_pdf_page_input(SseDeserializer deserializer);

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  (String, Map<String, bool>) sse_decode_record_string_map_string_bool_none(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, int) sse_decode_record_string_u_32(SseDeserializer deserializer);

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  (int, List<String>) sse_decode_record_u_32_list_string(
    SseDeserializer deserializer,
  );

  @protected
  ResultGrouping sse_decode_result_grouping(SseDeserializer deserializer);

  @protected
  ResultsOrder sse_decode_results_order(SseDeserializer deserializer);

  @protected
  SearchPageResult sse_decode_search_page_result(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  SearchScope sse_decode_search_scope(SseDeserializer deserializer);

  @protected
  SearchStreamUpdate sse_decode_search_stream_update(
    SseDeserializer deserializer,
  );

  @protected
  SemanticBookInput sse_decode_semantic_book_input(
    SseDeserializer deserializer,
  );

  @protected
  SemanticBookLineInput sse_decode_semantic_book_line_input(
    SseDeserializer deserializer,
  );

  @protected
  SemanticConfigInput sse_decode_semantic_config_input(
    SseDeserializer deserializer,
  );

  @protected
  SemanticExecutedMode sse_decode_semantic_executed_mode(
    SseDeserializer deserializer,
  );

  @protected
  SemanticGroupingMode sse_decode_semantic_grouping_mode(
    SseDeserializer deserializer,
  );

  @protected
  SemanticIndexDiff sse_decode_semantic_index_diff(
    SseDeserializer deserializer,
  );

  @protected
  SemanticIndexingSummary sse_decode_semantic_indexing_summary(
    SseDeserializer deserializer,
  );

  @protected
  SemanticLexicalMode sse_decode_semantic_lexical_mode(
    SseDeserializer deserializer,
  );

  @protected
  SemanticRemoveResult sse_decode_semantic_remove_result(
    SseDeserializer deserializer,
  );

  @protected
  SemanticResetResult sse_decode_semantic_reset_result(
    SseDeserializer deserializer,
  );

  @protected
  SemanticResultSource sse_decode_semantic_result_source(
    SseDeserializer deserializer,
  );

  @protected
  SemanticRetrievalMode sse_decode_semantic_retrieval_mode(
    SseDeserializer deserializer,
  );

  @protected
  SemanticSearchResponse sse_decode_semantic_search_response(
    SseDeserializer deserializer,
  );

  @protected
  SemanticSearchResult sse_decode_semantic_search_result(
    SseDeserializer deserializer,
  );

  @protected
  SemanticStatus sse_decode_semantic_status(SseDeserializer deserializer);

  @protected
  TestCase sse_decode_test_case(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WordMatchMode sse_decode_word_match_mode(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    RegexBenchmarker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    RegexBenchmarker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_Map_String_bool_None_None(
    Map<String, Map<String, bool>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_u_32_None(
    Map<String, int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_u_64_None(
    Map<String, BigInt> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_u_32_list_String_None(
    Map<int, List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    RegexBenchmarker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    SearchEngine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_search_result_Sse(
    RustStreamSink<List<SearchResult>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_search_stream_update_Sse(
    RustStreamSink<SearchStreamUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_benchmark_result(
    BenchmarkResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_benchmark_suite(
    BenchmarkSuite self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_book_count_result(
    BookCountResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_benchmark_result(
    BenchmarkResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_highlight_config(
    HighlightConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_highlight_pattern(
    HighlightPattern self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_result_grouping(
    ResultGrouping self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_result(
    SearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_semantic_config_input(
    SemanticConfigInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_semantic_grouping_mode(
    SemanticGroupingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_word_match_mode(
    WordMatchMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_count_result(CountResult self, SseSerializer serializer);

  @protected
  void sse_encode_document_input(DocumentInput self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_facet_count(FacetCount self, SseSerializer serializer);

  @protected
  void sse_encode_facet_counts_result(
    FacetCountsResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_highlight_config(
    HighlightConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_highlight_pattern(
    HighlightPattern self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_index_compatibility(
    IndexCompatibility self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_benchmark_result(
    List<BenchmarkResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_document_input(
    List<DocumentInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_facet_count(
    List<FacetCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_merged_sibling(
    List<MergedSibling> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pdf_index_line(
    List<PdfIndexLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pdf_page_input(
    List<PdfPageInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_map_string_bool_none(
    List<(String, Map<String, bool>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_32(
    List<(String, int)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_64(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_32_list_string(
    List<(int, List<String>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semantic_book_input(
    List<SemanticBookInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semantic_book_line_input(
    List<SemanticBookLineInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semantic_search_result(
    List<SemanticSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_test_case(List<TestCase> self, SseSerializer serializer);

  @protected
  void sse_encode_merged_sibling(MergedSibling self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_u_32_None(
    Map<String, int>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_benchmark_result(
    BenchmarkResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_highlight_config(
    HighlightConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_highlight_pattern(
    HighlightPattern? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_result_grouping(
    ResultGrouping? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_search_result(
    SearchResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_semantic_grouping_mode(
    SemanticGroupingMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_word_match_mode(
    WordMatchMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_index_line(PdfIndexLine self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_page_input(PdfPageInput self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_map_string_bool_none(
    (String, Map<String, bool>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_32(
    (String, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_list_string(
    (int, List<String>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_result_grouping(
    ResultGrouping self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_results_order(ResultsOrder self, SseSerializer serializer);

  @protected
  void sse_encode_search_page_result(
    SearchPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_search_scope(SearchScope self, SseSerializer serializer);

  @protected
  void sse_encode_search_stream_update(
    SearchStreamUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_book_input(
    SemanticBookInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_book_line_input(
    SemanticBookLineInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_config_input(
    SemanticConfigInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_executed_mode(
    SemanticExecutedMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_grouping_mode(
    SemanticGroupingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_index_diff(
    SemanticIndexDiff self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_indexing_summary(
    SemanticIndexingSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_lexical_mode(
    SemanticLexicalMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_remove_result(
    SemanticRemoveResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_reset_result(
    SemanticResetResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_result_source(
    SemanticResultSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_retrieval_mode(
    SemanticRetrievalMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_search_response(
    SemanticSearchResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_search_result(
    SemanticSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_semantic_status(
    SemanticStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_test_case(TestCase self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_word_match_mode(WordMatchMode self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRegexBenchmarker(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSearchEngine(
    int ptr,
  );
}
